### ISSUE TITLE
Error: Could not autoload puppet/parser/functions/ip_address: cannot load such file -- puppetx/ip

### ISSUE THREAD

**Issue by simonkurka** [inkblot/puppet-ipcalc#3]
When I'm trying to compile my manifests which use your module I receive the following error:

``` sh
# puppet master --compile puppetmaster.fritz.box --environment master
...
Error: Could not autoload puppet/parser/functions/ip_address: cannot load such file -- puppetx/ip
```

``` sh
# puppet agent --test
...
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/ip_address: no such file to load -- puppetx/ip at /etc/puppetlabs/code/environments/master/modules/foo/templates/bar.epp:25:13 on node puppetmaster.fritz.box
...
```

Do you have any clues how to solve this?

I run on Debian 8.2 with puppet 4.3.2 from the puppetlabs repos.

Thank you in advance!

**Comment by inkblot** [comment]
This is a known issue in recent versions of Puppet. Here is an example from `puppetserver`: https://tickets.puppetlabs.com/browse/SERVER-973

I'm not sure what to do about it other than wait to see if Puppet Labs fixes it.
