### ISSUE TITLE
little bug with puppet4 iteration + this module 

### ISSUE THREAD

**Issue by jamesmollison** [inkblot/puppet-ipcalc#5]
Hiya - I've just noticed that ipcalc is not chomping off /subnets from cidr after doing it once.  This is reproducible when dealing with ip_netmask/ip_broadcast/ip_network in a single profile.

I was able to duplicate this pretty consistently but it might be a pain to set up.  I'm using the example42/network module but that's irrelevant here.

So from this hiera:
```
profile::virtualinterfacehash:
 vlan33:
    ipaddr: '10.33.95.72/24'
```
and in the profile:
```
$virtualinterfacehash.each |$name, $ipinfo| { 
network::interface { "${name}":
      ipaddress         => ip_address($ipinfo["ipaddr"]),
      netmask           => ip_netmask($ipinfo["ipaddr"]),
      broadcast         => ip_broadcast($ipinfo["ipaddr"]),
      network           => ip_network($ipinfo["ipaddr"]),
```

The final output is :
```
auto vlan33
iface vlan33 inet static
    address 10.33.95.72
    netmask 255.255.255.0
    broadcast 10.33.95.255/24
    network 10.33.95.0/24
```

You see the last two lines barf this config - the cidr transform happens, but the /subnet is not stripped  This isn't an issue with just ip_broadcast or ip_network - having any two of those values (netmask/broadcast/network) means the second value (and any subsequent ones) will not strip the /subnet from the final output. 

Let me know if you need any more information from me about this issue

**Comment by inkblot** [comment]
That's the intended behavior of `ip_broadcast` and `ip_network`. These two functions produce a CIDR-pair. At the point where you're declaring your interface I think what you want instead of `ip_network($ipinfo["ipaddr")` is `ip_address(ip_network($ipinfo["ipaddr"]))`. Same with `ip_broadcast`.

**Comment by inkblot** [comment]
I'll add some example usage to the documentation.

**Comment by jamesmollison** [comment]
Ah that makes a lot of sense. Thankyou.
