### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by faxm0dem** [inkblot/puppet-ipcalc#6]
When trying to use IPv6 addresses, the module spinlocks:

```
☠ puppet apply -e '$a=ip_network("2a00:1450:400a:804::200e/64") notify{$a:}'

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
28878 faxmodem   20   0  232300  62724  12116 R 100.0  0.8   1:44.77 puppet
```

**Comment by inkblot** [comment]
My guess is that when it runs `range.to_a[offset]` to first realize the range of addresses and second fetch a specific index, that this is an enormous array. I'll have to put some thought into how to better handle this.

**Comment by faxm0dem** [comment]
Thanks!
